name: Build and Deploy Vue.js Project

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: clean
      run: npm cache clean --force
    

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    ## 서버에 아티팩트 전송
    - name: Transfer artifact
      uses: appleboy/scp-action@master
      env:
        WINDOWS_PC_IP: ${{ secrets.REMOTE_HOST }}       
        WINDOWS_PC_USERNAME: ${{ secrets.REMOTE_USER }}    
      with:
        username: ${{ secrets.REMOTE_USER }}
        host: ${{ secrets.REMOTE_HOST }}
        port: 22
        key: ${{ secrets.SSH_KEY }}
        rm: true
        source: "./dist"
        target: C:\Users\$WINDOWS_PC_USERNAME\Desktop
        ## 작업에 사용했던 dist 디렉토리를 경로상에서 제거
        strip_components: 1
              
          
      
       
