name: Build and Deploy Vue.js Project

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Copy files to Windows PC
      env:
        WINDOWS_PC_IP: ${{ secrets.REMOTE_HOST }}
        WINDOWS_PC_USERNAME: ${{ secrets.REMOTE_USER }}
        WINDOWS_PC_PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
      
      
      run: |
        # Windows PC로 파일 복사
        $securePassword = ConvertTo-SecureString $env:WINDOWS_PC_PASSWORD -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential ($env:WINDOWS_PC_USERNAME, $securePassword)
        $sourcePath = "dist" # 빌드된 파일의 경로를 수정해야 합니다.
        $destinationPath = "\\$env:WINDOWS_PC_IP\c$\Users\$env:WINDOWS_PC_USERNAME\Desktop\"
        Copy-Item -Path $sourcePath -Destination $destinationPath -Recurse -Force -Credential $credential

   
