name: Build and Deploy Vue.js Project

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: clean
      run: npm cache clean --force
    - name: Get ssh
      run: ls -l /home/runner/work/clone/.ssh/id_rsa
      

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
      
    - name: Copy files to Windows PC
      env:
        WINDOWS_PC_IP: ${{ secrets.REMOTE_HOST }}       
        WINDOWS_PC_USERNAME: ${{ secrets.REMOTE_USER }}                
        WINDOWS_PC_PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
      run: scp -i $RUNNER_WORKSPACE/.ssh/id_rsa -r ./dist $WINDOWS_PC_USERNAME@$WINDOWS_PC_IP:"C:\Users\$WINDOWS_PC_USERNAME\Desktop"

              
          
      
       
