name: Build and Deploy Vue.js Project

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: clean
      run: npm cache clean --force
    - name: Set ssh
      run: ssh-keygen -t rsa -b 4096 -C "your_email@example.com"
    - name: Get ssh
      run: ls -l /home/runner/work/clone
      

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: scp action
      # You may pin to the exact commit or the version.
      # uses: c0c1/scp-action@7c13f74869e81c70a71b04ab0a7087dbdee76ab4
      uses: c0c1/scp-action@v1.0
      env:
        WINDOWS_PC_IP: ${{ secrets.REMOTE_HOST }}       
        WINDOWS_PC_USERNAME: ${{ secrets.REMOTE_USER }}       
      with:
        # Sorce dir to deploy
        src: ./dist
        # SSH address
        host: ${{ secrets.REMOTE_HOST }}
        # Remote dir path
        remote: C:\Users\$WINDOWS_PC_USERNAME\Desktop
        # SSH Port
        #port: # optional, default is 22
        # SSH User name
        user: ${{ secrets.REMOTE_USER }}
        # Private key
        key: ${{ secrets.SSH_KEY }}
          
              
          
      
       
